# Generated by Django 2.2.12 on 2020-05-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pals',
            field=models.ManyToManyField(blank=True, null=True, to='core.Profile'),
        ),
    ]
