# Generated by Django 2.2.12 on 2020-05-30 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200530_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pals',
            field=models.ManyToManyField(blank=True, null=True, related_name='pals', to=settings.AUTH_USER_MODEL),
        ),
    ]
