# Generated by Django 2.2.12 on 2020-06-02 06:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20200601_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRequest',
            new_name='PalRequest',
        ),
    ]
